### ISSUE TITLE
Add support to propTypes

### ISSUE THREAD

**Issue by botteroxom** [egoist/vue-compile#238]
``` ts
 myProp: {
          type: Object as PropType<MyCustomType>,
          required: true,
},
```
```
 Unexpected token, expected "," (12:25)
  10 |     props: {
  11 |         myProp: {
> 12 |             type: Object as PropType<MyCustomType>,
     |                          ^
  13 |             required: true,
  14 |         },
  15 |         primary: Boolean,
  ```
    at Parser._raise (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:816:17)
    at Parser.raiseWithData (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:809:17)
    at Parser.raise (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:770:17)
    at Parser.unexpected (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:9893:16)
    at Parser.expect (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:9867:28)
    at Parser.parseObjectLike (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:11691:14)
    at Parser.parseExprAtom (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:11223:23)
    at Parser.parseExprSubscripts (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:10881:23)
    at Parser.parseUpdate (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:10861:21)
    at Parser.parseMaybeUnary (C:\...\AppData\Roaming\npm\node_modules\vue-compile\node_modules\@babel\parser\lib\index.js:10839:23)

**Comment by mesqueeb** [comment]
+1
I have the same issue!  : D

**Comment by mesqueeb** [comment]
@egoist can I sponsor this feature specifically with a certain amount?
